# Generated by Django 5.2.17 on 2026-10-10 14:18

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="อีเมล")),
                (
                    "student_or_staff_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="รหัสนักศึกษา/รหัสพนักงาน",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "ผู้ดูแลระบบ"), ("teacher", "ผู้สอน"), ("student", "ผู้เรียน")],
                        max_length=10,
                        verbose_name="บทบาท",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="ชื่อ")),
                ("last_name", models.CharField(max_length=150, verbose_name="นามสกุล")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งานได้")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="เข้าหน้า Django admin ได้"),
                ),
                (
                    "avatar_url",
                    models.FileField(
                        blank=True, max_length=255, upload_to="avatars/", verbose_name="รูปประจำตัว"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="วันที่สร้างบัญชี"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="สร้างโดย",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "ผู้ใช้",
                "verbose_name_plural": "ผู้ใช้",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        name="accounts_user_email_ci_unique",
                    )
                ],
            },
        ),
    ]
